# Site settings
title: WebRTC Bootstrap
email: sacha.nacar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  WebRTC Boostrap is a guide to all the necessary steps, frameworks, and terms to help you deploy your WebRTC solution.
baseurl: "/webrtc-bootstrap" # the subpath of your site, e.g. /blog/
url: "http://sachanacar.github.io" # the base hostname & protocol for your site
twitter_username: sachanacar
github_username:  sachanacar

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
